- name: variables from remote file
  hosts: local
  connection: local
  vars_files:
    - course.yml
  tasks:
    - name: print variables
      vars:
        COURSE: Ansible
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Trainer is {{ TRAINER }}"