- name: install packages
  hosts: all
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: nginx
        state: present
    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
    - name: Restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted