- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: nginx
        state: present
    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        state: started