- name: shell commands usage
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: command module test 
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: users_output
  - name: print output 
    ansible.builtin.debug:
      msg: "{{ users_output }}"
  - name: Change directory and check for the log files
    ansible.builtin.shell: 
      cmd: ls -ltrh | grep log > test.txt
      chdir : /var/log/
    register: test_file_output
  - name: print files output
    ansible.builtin.debug:
      msg: "{{ test_file_output }}"